#-------------------------------------------------------------------------------
# Makefile: psim
#-------------------------------------------------------------------------------

# Copyright (c) 2007 Peter Bui. All Rights Reserved.

# This software is provided 'as-is', without any express or implied warranty.
# In no event will the authors be held liable for any damages arising from the
# use of this software.

# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:

# 1. The origin of this software must not be misrepresented; you must not claim
# that you wrote the original software. If you use this software in a product,
# an acknowledgment in the product documentation would be appreciated but is
# not required.

# 2. Altered source versions must be plainly marked as such, and must not be
# misrepresented as being the original software.  

# 3. This notice may not be removed or altered from any source distribution.

# Peter Bui <pbui@cse.nd.edu>

#-------------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------------

SHELL		= /bin/sh
CC       	= gcc
CXX      	= g++

#-------------------------------------------------------------------------------
# Color Commands and Macros
#-------------------------------------------------------------------------------

MAKE_COLOR    	= $(shell tput setaf 5)
CC_COLOR      	= $(shell tput setaf 6)
LINK_COLOR      = $(shell tput setaf 2)
END_COLOR     	= $(shell tput sgr0)

MAKE_MSG	= echo '[$(MAKE_COLOR)MAKE$(END_COLOR)]   $(1)'
CC_MSG		= echo '    [$(CC_COLOR)$(1)$(END_COLOR)]   $(2)'
LINK_MSG	= echo '    [$(LINK_COLOR)LINK$(END_COLOR)] $(1)'

#-------------------------------------------------------------------------------
# Compiler and Linker Flags
#-------------------------------------------------------------------------------

CFLAGS   	= -Wall -Winline
CFLAGS	       += $(BCFLAGS) $(INCPATH)
CXXFLAGS 	= $(CFLAGS)

LINKFLAGS      	= -lm

#-------------------------------------------------------------------------------
# Include and Library Paths
#-------------------------------------------------------------------------------

INCPATH		= -I.
LIBPATH	 	= -L.

#-------------------------------------------------------------------------------
# Specific Targets and Objects
#-------------------------------------------------------------------------------

PASM_SRC	= pasm.cc psim_common.cc
PASM_OBJ   	= $(PASM_SRC:.cc=.o)
PASM_TGT   	= pasm

PSIM_SRC	= psim.cc psim_common.cc
PSIM_OBJ   	= $(PSIM_SRC:.cc=.o)
PSIM_TGT   	= psim

TARGETS	 	= $(PASM_TGT) $(PSIM_TGT)

#-------------------------------------------------------------------------------
# File Extension Handlers
#-------------------------------------------------------------------------------

.SUFFIXES:	.cc .c .o

.c.o:
	@$(call CC_MSG,CC,$(RELPATH)$@)
	@$(CC) $(CFLAGS) -o $@ -c $<

.cc.o:
	@$(call CC_MSG,CXX,$(RELPATH)$@)
	@$(CXX) $(CXXFLAGS) -o $@ -c $<

#-------------------------------------------------------------------------------
# General Targets
#-------------------------------------------------------------------------------

all: 	
	@$(call MAKE_MSG,'Building all object and target files')
	@$(MAKE) $(TARGETS)

phony:	clean depend update

clean:
	@$(call MAKE_MSG,'Removing all object and target files')
	@rm -f *.o $(TARGETS)

depend:
	@$(call MAKE_MSG,'Generating dependencies automagically')
	@rm -f Makefile.bak
	@mv Makefile Makefile.bak
	@sed '/^# DEPENDENCIES/,$$d' Makefile.bak > Makefile
	@echo '# DEPENDENCIES' >> Makefile
	@echo '' >> Makefile
	@$(CC) -MM *.cc >> Makefile
	@echo '' >> Makefile
	@echo -n '#-------------------------------------' >> Makefile
	@echo '------------------------------------------' >> Makefile
	@echo '# vim: sts=4 sw=4 ts=8 ft=make' >> Makefile
	@echo -n '#-------------------------------------' >> Makefile
	@echo '------------------------------------------' >> Makefile

update: clean depend all

#-------------------------------------------------------------------------------
# Specific Target Options
#-------------------------------------------------------------------------------

$(PASM_TGT):	$(PASM_OBJ)
	@$(call LINK_MSG,$(RELPATH)$@)
	@$(CXX) -o $@ $(LIBPATH) $(PASM_OBJ) $(LINKFLAGS) 

$(PSIM_TGT):	$(PSIM_OBJ)
	@$(call LINK_MSG,$(RELPATH)$@)
	@$(CXX) -o $@ $(LIBPATH) $(PSIM_OBJ) $(LINKFLAGS) 

#-------------------------------------------------------------------------------
# Autogenerated Dependencies
#-------------------------------------------------------------------------------

# DEPENDENCIES

pasm.o: pasm.cc psim.h
psim.o: psim.cc psim.h
psim_common.o: psim_common.cc psim.h

#-------------------------------------------------------------------------------
# vim: sts=4 sw=4 ts=8 ft=make
#-------------------------------------------------------------------------------
